services:
  db:
    image: postgres:16
    container_name: financas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: financas_pass
      POSTGRES_DB: financas
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
